apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: anishra102/mern-story-app-frontend
          ports:
            - containerPort: 80    
