name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Docker to Minikube
        run: minikube -p minikube dcoker-env | Invoke-Expression

      - name: Build Docker images
        run: |
          docker build -t anishra102/mern-story-app-backend ./backend
          docker build -t anishra102/mern-story-app-frontend ./frontend

      - name: Push Docker images
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push anishra102/mern-story-app-backend
          docker push anishra102/mern-story-app-frontend

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f mongo-deployment.yaml
          kubectl apply -f mongo-service.yaml
          kubectl apply -f backend-deployment.yaml
          kubectl apply -f backend-service.yaml
          kubectl apply -f frontend-deployment.yaml
          kubectl apply -f frontend-service.yaml
